services:
  minio:
    image: quay.io/minio/minio:RELEASE.2024-08-03T04-33-23Z
    container_name: minio
    ports:
      - 9000:9000
      - 9090:9090
    env_file:
      - .env
    # environment:
    #   - MINIO_ROOT_USER=admin
    #   - MINIO_ROOT_PASSWORD=nonprodpasswd
    #   - MINIO_BUCKET=flask
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    # hostname: minio
    volumes:
      - ./data/minio:/data
    command: server /data --console-address ":9090"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["python", "app.py"]
    env_file:
      - .env
    ports:
      - 5000:5000
    restart: always
    hostname: web
    depends_on:
      - minio
